"""Catalog of every numbered strategy in Kakushadze & Serur (SSRN 3247865).

The paper is marketed as "151 trading strategies"; its table of contents carries
175 numbered ``Strategy:`` entries once sub-strategies (2.40.1, 3.9.1, 10.3.1,
...) are counted individually.  All of them are listed here so the research
track covers the whole paper, each tagged with what it would take to run:

``implemented``
    Reproduced from the paper's formulas using ``stooq.daily`` OHLCV bars.
``substituted``
    Reproduced, but with a documented proxy for an input this universe lacks
    (a factor file, an ETF leg, an open-interest series).  ``note`` says what.
``not_implemented``
    Needs data outside daily equity bars.  ``requires`` says what.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

import pandas as pd


@dataclass(frozen=True)
class CatalogEntry:
    section: str
    title: str
    chapter: str
    chapter_title: str
    status: str
    strategy_keys: tuple[str, ...]
    requires: str
    note: str

    @property
    def is_runnable(self) -> bool:
        return self.status in ("implemented", "substituted")


CATALOG: tuple[CatalogEntry, ...] = (
    CatalogEntry(
        section='2.2',
        title='Covered call',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.3',
        title='Covered put',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.4',
        title='Protective put',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.5',
        title='Protective call',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.6',
        title='Bull call spread',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.7',
        title='Bull put spread',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.8',
        title='Bear call spread',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.9',
        title='Bear put spread',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.10',
        title='Long synthetic forward',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.11',
        title='Short synthetic forward',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.12',
        title='Long combo',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.13',
        title='Short combo',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.14',
        title='Bull call ladder',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.15',
        title='Bull put ladder',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.16',
        title='Bear call ladder',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.17',
        title='Bear put ladder',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.18',
        title='Calendar call spread',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.19',
        title='Calendar put spread',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.20',
        title='Diagonal call spread',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.21',
        title='Diagonal put spread',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.22',
        title='Long straddle',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.23',
        title='Long strangle',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.24',
        title='Long guts',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.25',
        title='Short straddle',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.26',
        title='Short strangle',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.27',
        title='Short guts',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.28',
        title='Long call synthetic straddle',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.29',
        title='Long put synthetic straddle',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.30',
        title='Short call synthetic straddle',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.31',
        title='Short put synthetic straddle',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.32',
        title='Covered short straddle',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.33',
        title='Covered short strangle',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.34',
        title='Strap',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.35',
        title='Strip',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.36',
        title='Call ratio backspread',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.37',
        title='Put ratio backspread',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.38',
        title='Ratio call spread',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.39',
        title='Ratio put spread',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.40',
        title='Long call butterﬂy',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.40.1',
        title='Modiﬁed call butterﬂy',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.41',
        title='Long put butterﬂy',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.41.1',
        title='Modiﬁed put butterﬂy',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.42',
        title='Short call butterﬂy',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.43',
        title='Short put butterﬂy',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.44',
        title='“Long” iron butterﬂy',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.45',
        title='“Short” iron butterﬂy',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.46',
        title='Long call condor',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.47',
        title='Long put condor',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.48',
        title='Short call condor',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.49',
        title='Short put condor',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.50',
        title='Long iron condor',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.51',
        title='Short iron condor',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.52',
        title='Long box',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.53',
        title='Collar',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.54',
        title='Bullish short seagull spread',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.55',
        title='Bearish long seagull spread',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.56',
        title='Bearish short seagull spread',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='2.57',
        title='Bullish long seagull spread',
        chapter='2',
        chapter_title='Options',
        status='not_implemented',
        strategy_keys=(),
        requires='options chains: strikes, expiries, premia, Greeks',
        note='',
    ),
    CatalogEntry(
        section='3.1',
        title='Price-momentum',
        chapter='3',
        chapter_title='Stocks',
        status='implemented',
        strategy_keys=('3.1.price_momentum', '3.1.price_momentum_long_only'),
        requires='',
        note='',
    ),
    CatalogEntry(
        section='3.2',
        title='Earnings-momentum',
        chapter='3',
        chapter_title='Stocks',
        status='not_implemented',
        strategy_keys=(),
        requires='quarterly earnings per share history (SUE)',
        note='',
    ),
    CatalogEntry(
        section='3.3',
        title='Value',
        chapter='3',
        chapter_title='Stocks',
        status='not_implemented',
        strategy_keys=(),
        requires='book value per share / book-to-price',
        note='',
    ),
    CatalogEntry(
        section='3.4',
        title='Low-volatility anomaly',
        chapter='3',
        chapter_title='Stocks',
        status='implemented',
        strategy_keys=('3.4.low_volatility',),
        requires='',
        note='',
    ),
    CatalogEntry(
        section='3.5',
        title='Implied volatility',
        chapter='3',
        chapter_title='Stocks',
        status='not_implemented',
        strategy_keys=(),
        requires='option-implied call and put volatilities',
        note='',
    ),
    CatalogEntry(
        section='3.6',
        title='Multifactor portfolio',
        chapter='3',
        chapter_title='Stocks',
        status='substituted',
        strategy_keys=('3.6.multifactor',),
        requires='',
        note='Blends the price-based factors available in stooq.daily (momentum, low-volatility, short-horizon reversal); the value and earnings legs of the paper need fundamental data.',
    ),
    CatalogEntry(
        section='3.7',
        title='Residual momentum',
        chapter='3',
        chapter_title='Stocks',
        status='substituted',
        strategy_keys=('3.7.residual_momentum',),
        requires='',
        note='MKT is proxied by the equal-weighted universe return; SMB and HML need a Fama-French factor file.',
    ),
    CatalogEntry(
        section='3.8',
        title='Pairs trading',
        chapter='3',
        chapter_title='Stocks',
        status='implemented',
        strategy_keys=('3.8.pairs_trading',),
        requires='',
        note='The pair is selected on each training window and frozen for the test window.',
    ),
    CatalogEntry(
        section='3.9',
        title='Mean-reversion – single cluster',
        chapter='3',
        chapter_title='Stocks',
        status='implemented',
        strategy_keys=('3.9.mean_reversion_single_cluster',),
        requires='',
        note='',
    ),
    CatalogEntry(
        section='3.9.1',
        title='Mean-reversion – multiple clusters',
        chapter='3',
        chapter_title='Stocks',
        status='substituted',
        strategy_keys=('3.9.1.mean_reversion_multi_cluster',),
        requires='',
        note="Clusters are learned from training-window return correlations; the paper's alternative is a vendor industry classification.",
    ),
    CatalogEntry(
        section='3.10',
        title='Mean-reversion – weighted regression',
        chapter='3',
        chapter_title='Stocks',
        status='substituted',
        strategy_keys=('3.10.mean_reversion_weighted_regression',),
        requires='',
        note='Loadings are the intercept plus training-window principal components; industry-based binary loadings need a classification file.',
    ),
    CatalogEntry(
        section='3.11',
        title='Single moving average',
        chapter='3',
        chapter_title='Stocks',
        status='implemented',
        strategy_keys=('3.11.single_moving_average',),
        requires='',
        note='',
    ),
    CatalogEntry(
        section='3.12',
        title='Two moving averages',
        chapter='3',
        chapter_title='Stocks',
        status='implemented',
        strategy_keys=('3.12.two_moving_averages',),
        requires='',
        note='Includes the Eq. (323) percentage stop-loss variant.',
    ),
    CatalogEntry(
        section='3.13',
        title='Three moving averages',
        chapter='3',
        chapter_title='Stocks',
        status='implemented',
        strategy_keys=('3.13.three_moving_averages',),
        requires='',
        note='',
    ),
    CatalogEntry(
        section='3.14',
        title='Support and resistance',
        chapter='3',
        chapter_title='Stocks',
        status='implemented',
        strategy_keys=('3.14.support_resistance',),
        requires='',
        note='',
    ),
    CatalogEntry(
        section='3.15',
        title='Channel',
        chapter='3',
        chapter_title='Stocks',
        status='implemented',
        strategy_keys=('3.15.channel',),
        requires='',
        note='Both the Eq. (331) reversion reading and the breakout reading are available.',
    ),
    CatalogEntry(
        section='3.16',
        title='Event-driven – M&A',
        chapter='3',
        chapter_title='Stocks',
        status='not_implemented',
        strategy_keys=(),
        requires='M&A deal terms and announcement dates',
        note='',
    ),
    CatalogEntry(
        section='3.17',
        title='Machine learning – single-stock KNN',
        chapter='3',
        chapter_title='Stocks',
        status='implemented',
        strategy_keys=('3.17.single_stock_knn',),
        requires='',
        note='Feature ranges and the neighbour pool are frozen from the training window.',
    ),
    CatalogEntry(
        section='3.18',
        title='Statistical arbitrage – optimization',
        chapter='3',
        chapter_title='Stocks',
        status='implemented',
        strategy_keys=('3.18.stat_arb_optimization', '3.18.1.stat_arb_dollar_neutral'),
        requires='',
        note="Section 3.18.1's dollar-neutrality constraint is a separate registered strategy.",
    ),
    CatalogEntry(
        section='3.18.1',
        title='Statistical arbitrage - dollar-neutrality',
        chapter='3',
        chapter_title='Stocks',
        status='implemented',
        strategy_keys=('3.18.1.stat_arb_dollar_neutral',),
        requires='',
        note='Eq. (354)-(358): the Lagrange-multiplier form of Section 3.18.',
    ),
    CatalogEntry(
        section='3.19',
        title='Market-making',
        chapter='3',
        chapter_title='Stocks',
        status='not_implemented',
        strategy_keys=(),
        requires='order book, quotes and fills (intraday microstructure)',
        note='',
    ),
    CatalogEntry(
        section='3.20',
        title='Alpha combos',
        chapter='3',
        chapter_title='Stocks',
        status='implemented',
        strategy_keys=('3.20.alpha_combo',),
        requires='',
        note='Component alphas are the other implemented strategies; the 11-step weighting recipe is reproduced verbatim.',
    ),
    CatalogEntry(
        section='4.1',
        title='Sector momentum rotation',
        chapter='4',
        chapter_title='Exchange-traded funds (ETFs)',
        status='substituted',
        strategy_keys=('4.1.momentum_rotation',),
        requires='',
        note='Run on the single-stock universe rather than sector ETFs; the construction is identical.',
    ),
    CatalogEntry(
        section='4.1.1',
        title='Sector momentum rotation with MA ﬁlter',
        chapter='4',
        chapter_title='Exchange-traded funds (ETFs)',
        status='substituted',
        strategy_keys=('4.1.1.momentum_rotation_ma_filter',),
        requires='',
        note='Run on the single-stock universe rather than sector ETFs.',
    ),
    CatalogEntry(
        section='4.1.2',
        title='Dual-momentum sector rotation',
        chapter='4',
        chapter_title='Exchange-traded funds (ETFs)',
        status='substituted',
        strategy_keys=('4.1.2.dual_momentum',),
        requires='',
        note='The absolute-momentum gate uses the equal-weighted universe index; the risk-off leg is cash rather than an uncorrelated ETF.',
    ),
    CatalogEntry(
        section='4.2',
        title='Alpha rotation',
        chapter='4',
        chapter_title='Exchange-traded funds (ETFs)',
        status='not_implemented',
        strategy_keys=(),
        requires='Fama-French factor returns',
        note='',
    ),
    CatalogEntry(
        section='4.3',
        title='R-squared',
        chapter='4',
        chapter_title='Exchange-traded funds (ETFs)',
        status='substituted',
        strategy_keys=('4.3.r_squared',),
        requires='',
        note='Single-factor market model; SMB, HML and MOM need a Fama-French factor file.',
    ),
    CatalogEntry(
        section='4.4',
        title='Mean-reversion',
        chapter='4',
        chapter_title='Exchange-traded funds (ETFs)',
        status='implemented',
        strategy_keys=('4.4.mean_reversion_ibs',),
        requires='',
        note='Internal Bar Strength computed from stooq.daily high/low/close.',
    ),
    CatalogEntry(
        section='4.5',
        title='Leveraged ETFs (LETFs)',
        chapter='4',
        chapter_title='Exchange-traded funds (ETFs)',
        status='not_implemented',
        strategy_keys=(),
        requires='leveraged and inverse ETF price series',
        note='',
    ),
    CatalogEntry(
        section='4.6',
        title='Multi-asset trend following',
        chapter='4',
        chapter_title='Exchange-traded funds (ETFs)',
        status='implemented',
        strategy_keys=('4.6.multi_asset_trend',),
        requires='',
        note='All three Eq. (371)-(373) weighting schemes.',
    ),
    CatalogEntry(
        section='5.2',
        title='Bullets',
        chapter='5',
        chapter_title='Fixed Income',
        status='not_implemented',
        strategy_keys=(),
        requires='bond prices, yield curves, swap rates, durations',
        note='',
    ),
    CatalogEntry(
        section='5.3',
        title='Barbells',
        chapter='5',
        chapter_title='Fixed Income',
        status='not_implemented',
        strategy_keys=(),
        requires='bond prices, yield curves, swap rates, durations',
        note='',
    ),
    CatalogEntry(
        section='5.4',
        title='Ladders',
        chapter='5',
        chapter_title='Fixed Income',
        status='not_implemented',
        strategy_keys=(),
        requires='bond prices, yield curves, swap rates, durations',
        note='',
    ),
    CatalogEntry(
        section='5.5',
        title='Bond immunization',
        chapter='5',
        chapter_title='Fixed Income',
        status='not_implemented',
        strategy_keys=(),
        requires='bond prices, yield curves, swap rates, durations',
        note='',
    ),
    CatalogEntry(
        section='5.6',
        title='Dollar-duration-neutral butterﬂy',
        chapter='5',
        chapter_title='Fixed Income',
        status='not_implemented',
        strategy_keys=(),
        requires='bond prices, yield curves, swap rates, durations',
        note='',
    ),
    CatalogEntry(
        section='5.7',
        title='Fifty-ﬁfty butterﬂy',
        chapter='5',
        chapter_title='Fixed Income',
        status='not_implemented',
        strategy_keys=(),
        requires='bond prices, yield curves, swap rates, durations',
        note='',
    ),
    CatalogEntry(
        section='5.8',
        title='Regression-weighted butterﬂy',
        chapter='5',
        chapter_title='Fixed Income',
        status='not_implemented',
        strategy_keys=(),
        requires='bond prices, yield curves, swap rates, durations',
        note='',
    ),
    CatalogEntry(
        section='5.8.1',
        title='Maturity-weighted butterﬂy',
        chapter='5',
        chapter_title='Fixed Income',
        status='not_implemented',
        strategy_keys=(),
        requires='bond prices, yield curves, swap rates, durations',
        note='',
    ),
    CatalogEntry(
        section='5.9',
        title='Low-risk factor',
        chapter='5',
        chapter_title='Fixed Income',
        status='not_implemented',
        strategy_keys=(),
        requires='bond prices, yield curves, swap rates, durations',
        note='',
    ),
    CatalogEntry(
        section='5.10',
        title='Value factor',
        chapter='5',
        chapter_title='Fixed Income',
        status='not_implemented',
        strategy_keys=(),
        requires='bond prices, yield curves, swap rates, durations',
        note='',
    ),
    CatalogEntry(
        section='5.11',
        title='Carry factor',
        chapter='5',
        chapter_title='Fixed Income',
        status='not_implemented',
        strategy_keys=(),
        requires='bond prices, yield curves, swap rates, durations',
        note='',
    ),
    CatalogEntry(
        section='5.12',
        title='Rolling down the yield curve',
        chapter='5',
        chapter_title='Fixed Income',
        status='not_implemented',
        strategy_keys=(),
        requires='bond prices, yield curves, swap rates, durations',
        note='',
    ),
    CatalogEntry(
        section='5.13',
        title='Yield curve spread (ﬂatteners & steepeners)',
        chapter='5',
        chapter_title='Fixed Income',
        status='not_implemented',
        strategy_keys=(),
        requires='bond prices, yield curves, swap rates, durations',
        note='',
    ),
    CatalogEntry(
        section='5.14',
        title='CDS basis arbitrage',
        chapter='5',
        chapter_title='Fixed Income',
        status='not_implemented',
        strategy_keys=(),
        requires='bond prices, yield curves, swap rates, durations',
        note='',
    ),
    CatalogEntry(
        section='5.15',
        title='Swap-spread arbitrage',
        chapter='5',
        chapter_title='Fixed Income',
        status='not_implemented',
        strategy_keys=(),
        requires='bond prices, yield curves, swap rates, durations',
        note='',
    ),
    CatalogEntry(
        section='6.2',
        title='Cash-and-carry arbitrage',
        chapter='6',
        chapter_title='Indexes',
        status='not_implemented',
        strategy_keys=(),
        requires='index futures prices and financing rates',
        note='',
    ),
    CatalogEntry(
        section='6.3',
        title='Dispersion trading in equity indexes',
        chapter='6',
        chapter_title='Indexes',
        status='not_implemented',
        strategy_keys=(),
        requires='index constituents plus options on the index and its constituents',
        note='',
    ),
    CatalogEntry(
        section='6.3.1',
        title='Dispersion trading – subset portfolio',
        chapter='6',
        chapter_title='Indexes',
        status='not_implemented',
        strategy_keys=(),
        requires='index constituents plus options on the index and its constituents',
        note='',
    ),
    CatalogEntry(
        section='6.4',
        title='Intraday arbitrage between index ETFs',
        chapter='6',
        chapter_title='Indexes',
        status='not_implemented',
        strategy_keys=(),
        requires='intraday quotes for two index ETFs',
        note='',
    ),
    CatalogEntry(
        section='6.5',
        title='Index volatility targeting with risk-free asset',
        chapter='6',
        chapter_title='Indexes',
        status='substituted',
        strategy_keys=('6.5.volatility_targeting',),
        requires='',
        note='Risky asset is the equal-weighted universe index; the cash leg earns zero rather than the T-bill rate.',
    ),
    CatalogEntry(
        section='7.2',
        title='VIX futures basis trading',
        chapter='7',
        chapter_title='Volatility',
        status='not_implemented',
        strategy_keys=(),
        requires='VIX/variance-swap and option-implied volatility data',
        note='',
    ),
    CatalogEntry(
        section='7.3',
        title='Volatility carry with two ETNs',
        chapter='7',
        chapter_title='Volatility',
        status='not_implemented',
        strategy_keys=(),
        requires='VIX/variance-swap and option-implied volatility data',
        note='',
    ),
    CatalogEntry(
        section='7.3.1',
        title='Hedging short VXX with VIX futures',
        chapter='7',
        chapter_title='Volatility',
        status='not_implemented',
        strategy_keys=(),
        requires='VIX/variance-swap and option-implied volatility data',
        note='',
    ),
    CatalogEntry(
        section='7.4',
        title='Volatility risk premium',
        chapter='7',
        chapter_title='Volatility',
        status='not_implemented',
        strategy_keys=(),
        requires='VIX/variance-swap and option-implied volatility data',
        note='',
    ),
    CatalogEntry(
        section='7.4.1',
        title='Volatility risk premium with Gamma hedging',
        chapter='7',
        chapter_title='Volatility',
        status='not_implemented',
        strategy_keys=(),
        requires='VIX/variance-swap and option-implied volatility data',
        note='',
    ),
    CatalogEntry(
        section='7.5',
        title='Volatility skew – long risk reversal',
        chapter='7',
        chapter_title='Volatility',
        status='not_implemented',
        strategy_keys=(),
        requires='VIX/variance-swap and option-implied volatility data',
        note='',
    ),
    CatalogEntry(
        section='7.6',
        title='Volatility trading with variance swaps',
        chapter='7',
        chapter_title='Volatility',
        status='not_implemented',
        strategy_keys=(),
        requires='VIX/variance-swap and option-implied volatility data',
        note='',
    ),
    CatalogEntry(
        section='8.1',
        title='Moving averages with HP ﬁlter',
        chapter='8',
        chapter_title='Foreign Exchange (FX)',
        status='not_implemented',
        strategy_keys=(),
        requires='FX spot rates, forward points and policy rates',
        note='',
    ),
    CatalogEntry(
        section='8.2',
        title='Carry trade',
        chapter='8',
        chapter_title='Foreign Exchange (FX)',
        status='not_implemented',
        strategy_keys=(),
        requires='FX spot rates, forward points and policy rates',
        note='',
    ),
    CatalogEntry(
        section='8.2.1',
        title='High-minus-low carry',
        chapter='8',
        chapter_title='Foreign Exchange (FX)',
        status='not_implemented',
        strategy_keys=(),
        requires='FX spot rates, forward points and policy rates',
        note='',
    ),
    CatalogEntry(
        section='8.3',
        title='Dollar carry trade',
        chapter='8',
        chapter_title='Foreign Exchange (FX)',
        status='not_implemented',
        strategy_keys=(),
        requires='FX spot rates, forward points and policy rates',
        note='',
    ),
    CatalogEntry(
        section='8.4',
        title='Momentum & carry combo',
        chapter='8',
        chapter_title='Foreign Exchange (FX)',
        status='not_implemented',
        strategy_keys=(),
        requires='FX spot rates, forward points and policy rates',
        note='',
    ),
    CatalogEntry(
        section='8.5',
        title='FX triangular arbitrage',
        chapter='8',
        chapter_title='Foreign Exchange (FX)',
        status='not_implemented',
        strategy_keys=(),
        requires='FX spot rates, forward points and policy rates',
        note='',
    ),
    CatalogEntry(
        section='9.1',
        title='Roll yields',
        chapter='9',
        chapter_title='Commodities',
        status='not_implemented',
        strategy_keys=(),
        requires='commodity futures curves and hedging-pressure data',
        note='',
    ),
    CatalogEntry(
        section='9.2',
        title='Trading based on hedging pressure',
        chapter='9',
        chapter_title='Commodities',
        status='not_implemented',
        strategy_keys=(),
        requires='commodity futures curves and hedging-pressure data',
        note='',
    ),
    CatalogEntry(
        section='9.3',
        title='Portfolio diversiﬁcation with commodities',
        chapter='9',
        chapter_title='Commodities',
        status='not_implemented',
        strategy_keys=(),
        requires='commodity futures curves and hedging-pressure data',
        note='',
    ),
    CatalogEntry(
        section='9.4',
        title='Value',
        chapter='9',
        chapter_title='Commodities',
        status='not_implemented',
        strategy_keys=(),
        requires='commodity futures curves and hedging-pressure data',
        note='',
    ),
    CatalogEntry(
        section='9.5',
        title='Skewness premium',
        chapter='9',
        chapter_title='Commodities',
        status='not_implemented',
        strategy_keys=(),
        requires='commodity futures curves and hedging-pressure data',
        note='',
    ),
    CatalogEntry(
        section='9.6',
        title='Trading with pricing models',
        chapter='9',
        chapter_title='Commodities',
        status='not_implemented',
        strategy_keys=(),
        requires='commodity futures curves and hedging-pressure data',
        note='',
    ),
    CatalogEntry(
        section='10.1',
        title='Hedging risk with futures',
        chapter='10',
        chapter_title='Futures',
        status='not_implemented',
        strategy_keys=(),
        requires='futures term structure, volume and open interest',
        note='',
    ),
    CatalogEntry(
        section='10.1.1',
        title='Cross-hedging',
        chapter='10',
        chapter_title='Futures',
        status='not_implemented',
        strategy_keys=(),
        requires='futures term structure, volume and open interest',
        note='',
    ),
    CatalogEntry(
        section='10.1.2',
        title='Interest rate risk hedging',
        chapter='10',
        chapter_title='Futures',
        status='not_implemented',
        strategy_keys=(),
        requires='futures term structure, volume and open interest',
        note='',
    ),
    CatalogEntry(
        section='10.2',
        title='Calendar spread',
        chapter='10',
        chapter_title='Futures',
        status='not_implemented',
        strategy_keys=(),
        requires='futures term structure, volume and open interest',
        note='',
    ),
    CatalogEntry(
        section='10.3',
        title='Contrarian trading (mean-reversion)',
        chapter='10',
        chapter_title='Futures',
        status='substituted',
        strategy_keys=('10.3.contrarian',),
        requires='',
        note='Run on equities rather than futures; the weighting algebra is unchanged.',
    ),
    CatalogEntry(
        section='10.3.1',
        title='Contrarian trading – market activity',
        chapter='10',
        chapter_title='Futures',
        status='substituted',
        strategy_keys=('10.3.1.contrarian_market_activity',),
        requires='',
        note='Volume filter only - cash equities have no open-interest series.',
    ),
    CatalogEntry(
        section='10.4',
        title='Trend following (momentum)',
        chapter='10',
        chapter_title='Futures',
        status='substituted',
        strategy_keys=('10.4.trend_following',),
        requires='',
        note='Run on equities rather than futures; includes the tanh smoothing and dollar-neutral demeaning refinements.',
    ),
    CatalogEntry(
        section='11.2',
        title='Carry, equity tranche – index hedging',
        chapter='11',
        chapter_title='Structured Assets',
        status='not_implemented',
        strategy_keys=(),
        requires='CDO/CDS tranche quotes and MBS pool data',
        note='',
    ),
    CatalogEntry(
        section='11.3',
        title='Carry, senior/mezzanine – index hedging',
        chapter='11',
        chapter_title='Structured Assets',
        status='not_implemented',
        strategy_keys=(),
        requires='CDO/CDS tranche quotes and MBS pool data',
        note='',
    ),
    CatalogEntry(
        section='11.4',
        title='Carry – tranche hedging',
        chapter='11',
        chapter_title='Structured Assets',
        status='not_implemented',
        strategy_keys=(),
        requires='CDO/CDS tranche quotes and MBS pool data',
        note='',
    ),
    CatalogEntry(
        section='11.5',
        title='Carry – CDS hedging',
        chapter='11',
        chapter_title='Structured Assets',
        status='not_implemented',
        strategy_keys=(),
        requires='CDO/CDS tranche quotes and MBS pool data',
        note='',
    ),
    CatalogEntry(
        section='11.6',
        title='CDOs – curve trades',
        chapter='11',
        chapter_title='Structured Assets',
        status='not_implemented',
        strategy_keys=(),
        requires='CDO/CDS tranche quotes and MBS pool data',
        note='',
    ),
    CatalogEntry(
        section='11.7',
        title='Mortgage-backed security (MBS) trading',
        chapter='11',
        chapter_title='Structured Assets',
        status='not_implemented',
        strategy_keys=(),
        requires='CDO/CDS tranche quotes and MBS pool data',
        note='',
    ),
    CatalogEntry(
        section='12.1',
        title='Convertible arbitrage',
        chapter='12',
        chapter_title='Convertibles',
        status='not_implemented',
        strategy_keys=(),
        requires='convertible bond terms and option-adjusted spreads',
        note='',
    ),
    CatalogEntry(
        section='12.2',
        title='Convertible option-adjusted spread',
        chapter='12',
        chapter_title='Convertibles',
        status='not_implemented',
        strategy_keys=(),
        requires='convertible bond terms and option-adjusted spreads',
        note='',
    ),
    CatalogEntry(
        section='13.1',
        title='Municipal bond tax arbitrage',
        chapter='13',
        chapter_title='Tax Arbitrage',
        status='not_implemented',
        strategy_keys=(),
        requires='municipal/cross-border bond yields and tax rates',
        note='',
    ),
    CatalogEntry(
        section='13.2',
        title='Cross-border tax arbitrage',
        chapter='13',
        chapter_title='Tax Arbitrage',
        status='not_implemented',
        strategy_keys=(),
        requires='municipal/cross-border bond yields and tax rates',
        note='',
    ),
    CatalogEntry(
        section='13.2.1',
        title='Cross-border tax arbitrage with options',
        chapter='13',
        chapter_title='Tax Arbitrage',
        status='not_implemented',
        strategy_keys=(),
        requires='municipal/cross-border bond yields and tax rates',
        note='',
    ),
    CatalogEntry(
        section='14.1',
        title='Inﬂation hedging – inﬂation swaps',
        chapter='14',
        chapter_title='Miscellaneous Assets',
        status='not_implemented',
        strategy_keys=(),
        requires='inflation swaps, TIPS, weather and energy data',
        note='',
    ),
    CatalogEntry(
        section='14.2',
        title='TIPS-Treasury arbitrage',
        chapter='14',
        chapter_title='Miscellaneous Assets',
        status='not_implemented',
        strategy_keys=(),
        requires='inflation swaps, TIPS, weather and energy data',
        note='',
    ),
    CatalogEntry(
        section='14.3',
        title='Weather risk – demand hedging',
        chapter='14',
        chapter_title='Miscellaneous Assets',
        status='not_implemented',
        strategy_keys=(),
        requires='inflation swaps, TIPS, weather and energy data',
        note='',
    ),
    CatalogEntry(
        section='14.4',
        title='Energy – spark spread',
        chapter='14',
        chapter_title='Miscellaneous Assets',
        status='not_implemented',
        strategy_keys=(),
        requires='inflation swaps, TIPS, weather and energy data',
        note='',
    ),
    CatalogEntry(
        section='15.1',
        title='Buying and holding distressed debt',
        chapter='15',
        chapter_title='Distressed Assets',
        status='not_implemented',
        strategy_keys=(),
        requires='distressed debt prices and credit/bankruptcy data',
        note='',
    ),
    CatalogEntry(
        section='15.2',
        title='Active distressed investing',
        chapter='15',
        chapter_title='Distressed Assets',
        status='not_implemented',
        strategy_keys=(),
        requires='distressed debt prices and credit/bankruptcy data',
        note='',
    ),
    CatalogEntry(
        section='15.2.1',
        title='Planning a reorganization',
        chapter='15',
        chapter_title='Distressed Assets',
        status='not_implemented',
        strategy_keys=(),
        requires='distressed debt prices and credit/bankruptcy data',
        note='',
    ),
    CatalogEntry(
        section='15.2.2',
        title='Buying outstanding debt',
        chapter='15',
        chapter_title='Distressed Assets',
        status='not_implemented',
        strategy_keys=(),
        requires='distressed debt prices and credit/bankruptcy data',
        note='',
    ),
    CatalogEntry(
        section='15.2.3',
        title='Loan-to-own',
        chapter='15',
        chapter_title='Distressed Assets',
        status='not_implemented',
        strategy_keys=(),
        requires='distressed debt prices and credit/bankruptcy data',
        note='',
    ),
    CatalogEntry(
        section='15.3',
        title='Distress risk puzzle',
        chapter='15',
        chapter_title='Distressed Assets',
        status='not_implemented',
        strategy_keys=(),
        requires='distressed debt prices and credit/bankruptcy data',
        note='',
    ),
    CatalogEntry(
        section='15.3.1',
        title='Distress risk puzzle – risk management',
        chapter='15',
        chapter_title='Distressed Assets',
        status='not_implemented',
        strategy_keys=(),
        requires='distressed debt prices and credit/bankruptcy data',
        note='',
    ),
    CatalogEntry(
        section='16.2',
        title='Mixed-asset diversiﬁcation with real estate',
        chapter='16',
        chapter_title='Real Estate',
        status='not_implemented',
        strategy_keys=(),
        requires='property indexes and REIT/regional data',
        note='',
    ),
    CatalogEntry(
        section='16.3',
        title='Intra-asset diversiﬁcation within real estate',
        chapter='16',
        chapter_title='Real Estate',
        status='not_implemented',
        strategy_keys=(),
        requires='property indexes and REIT/regional data',
        note='',
    ),
    CatalogEntry(
        section='16.3.1',
        title='Property type diversiﬁcation',
        chapter='16',
        chapter_title='Real Estate',
        status='not_implemented',
        strategy_keys=(),
        requires='property indexes and REIT/regional data',
        note='',
    ),
    CatalogEntry(
        section='16.3.2',
        title='Economic diversiﬁcation',
        chapter='16',
        chapter_title='Real Estate',
        status='not_implemented',
        strategy_keys=(),
        requires='property indexes and REIT/regional data',
        note='',
    ),
    CatalogEntry(
        section='16.3.3',
        title='Property type and geographic diversiﬁcation',
        chapter='16',
        chapter_title='Real Estate',
        status='not_implemented',
        strategy_keys=(),
        requires='property indexes and REIT/regional data',
        note='',
    ),
    CatalogEntry(
        section='16.4',
        title='Real estate momentum – regional approach',
        chapter='16',
        chapter_title='Real Estate',
        status='not_implemented',
        strategy_keys=(),
        requires='property indexes and REIT/regional data',
        note='',
    ),
    CatalogEntry(
        section='16.5',
        title='Inﬂation hedging with real estate',
        chapter='16',
        chapter_title='Real Estate',
        status='not_implemented',
        strategy_keys=(),
        requires='property indexes and REIT/regional data',
        note='',
    ),
    CatalogEntry(
        section='16.6',
        title='Fix-and-ﬂip',
        chapter='16',
        chapter_title='Real Estate',
        status='not_implemented',
        strategy_keys=(),
        requires='property indexes and REIT/regional data',
        note='',
    ),
    CatalogEntry(
        section='17.2',
        title='Money laundering – the dark side of cash',
        chapter='17',
        chapter_title='Cash',
        status='not_implemented',
        strategy_keys=(),
        requires='money-market, repo and lending data',
        note='',
    ),
    CatalogEntry(
        section='17.3',
        title='Liquidity management',
        chapter='17',
        chapter_title='Cash',
        status='not_implemented',
        strategy_keys=(),
        requires='money-market, repo and lending data',
        note='',
    ),
    CatalogEntry(
        section='17.4',
        title='Repurchase agreement (REPO)',
        chapter='17',
        chapter_title='Cash',
        status='not_implemented',
        strategy_keys=(),
        requires='money-market, repo and lending data',
        note='',
    ),
    CatalogEntry(
        section='17.5',
        title='Pawnbroking',
        chapter='17',
        chapter_title='Cash',
        status='not_implemented',
        strategy_keys=(),
        requires='money-market, repo and lending data',
        note='',
    ),
    CatalogEntry(
        section='17.6',
        title='Loan sharking',
        chapter='17',
        chapter_title='Cash',
        status='not_implemented',
        strategy_keys=(),
        requires='money-market, repo and lending data',
        note='',
    ),
    CatalogEntry(
        section='18.2',
        title='Artiﬁcial neural network (ANN)',
        chapter='18',
        chapter_title='Cryptocurrencies',
        status='not_implemented',
        strategy_keys=(),
        requires='crypto price and social-sentiment feeds',
        note='',
    ),
    CatalogEntry(
        section='18.3',
        title='Sentiment analysis – na¨ ıve Bayes Bernoulli',
        chapter='18',
        chapter_title='Cryptocurrencies',
        status='not_implemented',
        strategy_keys=(),
        requires='crypto price and social-sentiment feeds',
        note='',
    ),
    CatalogEntry(
        section='19.2',
        title='Fundamental macro momentum',
        chapter='19',
        chapter_title='Global Macro',
        status='not_implemented',
        strategy_keys=(),
        requires='macroeconomic releases and cross-country asset data',
        note='',
    ),
    CatalogEntry(
        section='19.3',
        title='Global macro inﬂation hedge',
        chapter='19',
        chapter_title='Global Macro',
        status='not_implemented',
        strategy_keys=(),
        requires='macroeconomic releases and cross-country asset data',
        note='',
    ),
    CatalogEntry(
        section='19.4',
        title='Global ﬁxed-income strategy',
        chapter='19',
        chapter_title='Global Macro',
        status='not_implemented',
        strategy_keys=(),
        requires='macroeconomic releases and cross-country asset data',
        note='',
    ),
    CatalogEntry(
        section='19.5',
        title='Trading on economic announcements',
        chapter='19',
        chapter_title='Global Macro',
        status='not_implemented',
        strategy_keys=(),
        requires='macroeconomic releases and cross-country asset data',
        note='',
    )
)


def as_frame(entries: Iterable[CatalogEntry] | None = None) -> pd.DataFrame:
    entries = list(entries if entries is not None else CATALOG)
    return pd.DataFrame(
        [
            {
                "section": e.section,
                "chapter": e.chapter_title,
                "title": e.title,
                "status": e.status,
                "strategies": ", ".join(e.strategy_keys),
                "requires": e.requires,
                "note": e.note,
            }
            for e in entries
        ]
    )


def runnable() -> list[CatalogEntry]:
    return [e for e in CATALOG if e.is_runnable]


def by_section(section: str) -> CatalogEntry:
    for entry in CATALOG:
        if entry.section == section:
            return entry
    raise KeyError(f"no catalog entry for section {section}")


def summary() -> pd.DataFrame:
    """Per-chapter counts of implemented / substituted / not-implemented."""
    frame = as_frame()
    pivot = (
        frame.pivot_table(index="chapter", columns="status", values="section", aggfunc="count")
        .fillna(0)
        .astype(int)
    )
    pivot["total"] = pivot.sum(axis=1)
    return pivot.sort_values("total", ascending=False)
